### ISSUE TITLE
Exception on track revenue

### ISSUE THREAD

**Issue by paradizIscool** [adjust/unity_sdk#102]
Hi,

We've got some crashs when tracking revenue on ios.

Here is the crash (reporting by firebase crash report)
        if (revenue != -1 || currency != NULL) {
            NSString *stringCurrency = [NSString stringWithUTF8String:currency];
            [event setRevenue:revenue currency:stringCurrency];
        }

It seems that the currency might be null in some cases, even if revenue != -1, so NSString *stringCurrency = [NSString stringWithUTF8String:currency]; raises an exception (see https://developer.apple.com/reference/foundation/nsstring/1497379-stringwithutf8string)

**Comment by uerceg** [comment]
Hi @paradizIscool,

Nice catch. 👍  Handing of this case will be added to v4.11.1.

Will keep you posted on this issue about the progress.

Cheers

**Comment by uerceg** [comment]
Hi @paradizIscool 

Should be fixed in just released v4.11.1: https://github.com/adjust/unity_sdk/releases/tag/v4.11.1

Let us know if you face this or any other issue.

Cheers
