### ISSUE TITLE
Sending params with Event tracking

### ISSUE THREAD

**Issue by alamboley** [adjust/unity_sdk#117]
Hello,

Moving from Appsflyer to Adjust, I've to sent custom params (let say which character has been choosen for example) to an event. Does `Callback parameters` is the way to do it? The documentation is a ambiguous.

Example:
```c#
AdjustEvent adjustEvent = new AdjustEvent("abc123");

adjustEvent.addCallbackParameter("character", "John");
adjustEvent.addCallbackParameter("character_strength", "5");

Adjust.trackEvent(adjustEvent);
```

**Comment by uerceg** [comment]
Hi @alamboley 

Sounds like this is the option you are looking for. On the Adjust dashboard, you have event which you have created and that has `abc123` token. For it, you can set up callback URL which, when ever event is tracked, our backend will trigger and in there you format your URL and add what ever placeholders you would like to receive upon callback ping.

In case some of the things you want to see in that callback request from our backend to your servers which are only obtainable during app lifetime, this is the way how you can instruct to each key-value pair you set with call to `addCallbackParameter` method gets appended to your callback URL from the dashboard.

**Comment by alamboley** [comment]
Hi @uerceg, thanks for the answer but I'm a bit in trouble.

I will take an other example than Appsflyer with Google Analytics. Let say that I've an event:
```c#
googleAnalytics.LogEvent("Achievement", "Unlocked", "Slay 10 dragons", 5);
```

Does `addCallbackParameter` is the way to do it? I mean, I don't need callback URL, I just need to have a nice graph showing for specific events some custom data. The documentation isn't clear, but as I understand Adjust is not something like Google Analytics, right? It is more oriented on in app and sending data to other services.

The Web Analyst team send me to this SDK, but I'm not sure they have fully understand your product.

**Comment by uerceg** [comment]
@alamboley 

I am still not sure I understand exactly what are you trying to achieve, probably since I am not really knowledgable in how Google Analytics dashboard work in this case. If you track event like above with Google Analytics, which options are you having on their dashboard later? Is it like, what ever you attach to the event, you have access to this data later on the dashboard and can do some actions based on that data (filter, etc)?

**Comment by alamboley** [comment]
> Is it like, what ever you attach to the event, you have access to this data later on the dashboard and can do some actions based on that data (filter, etc)?

Yes, exactly.

**Comment by uerceg** [comment]
To be honest, I am not sure about this, this is definitely something that our Account Managers would be able to help you with. So when it comes to this, either ping you dedicated AM or simply send email with this question (and maybe referencing this issue) to support@adjust.com.

**Comment by wei780901** [comment]
I have same question.
It's mean I need creat my HttpServer to keep my callbackparameter?
Dashborad just show the event count? 

Thank you~

**Comment by uerceg** [comment]
@alamboley @wei780901 

Callback parameters on our platform are made to be sent via callbacks to an S3 bucket or client BI (so if you wanna get it like this, yes, it requires your own backend server to run). In same way, partner parameters are used to be sent to one of the partners. But in both cases we do not display contents of these parameters in our dashboard.

**Comment by wei780901** [comment]
@uerceg 
I see, Thank for your answer

**Comment by alamboley** [comment]
@uerceg thanks for the detailed explanations.
