### ISSUE TITLE
Plugin Crash on iOS 10 devices.

### ISSUE THREAD

**Issue by okanulas** [adjust/unity_sdk#118]
Hi,

I've been trying to update the plugin to version the 4.12.1 from 4.11.5 but the plugin crashes when trying to start the Adjust. Plugin is working on iOS version 11.2.5 but i get an error when trying to run on iOS 10.2. The problem is at the _AdjustLaunchApp function in AdjustUnity.mm.  There is some problem when setting UserAgent, DefaultTracker and SceneName. I added the lines that causes the crash below.

NSString *stringUserAgent = [NSString stringWithUTF8String:userAgent];
NSString *stringDefaultTracker = [NSString stringWithUTF8String:defaultTracker];
NSString *stringSceneName = [NSString stringWithUTF8String:sceneName];

Thank You.
Okan

**Comment by uerceg** [comment]
@okanulas 

Can you provide us with code you are using to initialise SDK (feel free to obfuscate private information such as app token)?

Also, would it be possible for you to zip `Adjust` folder from your `Assets` folder and attach it in here?

Thanks in advance.

**Comment by okanulas** [comment]
@uerceg 

I thought that something in our code base could cause the crashes so i've tested the example project in the adjust's unity package. 

This is the package i'm using > https://github.com/adjust/unity_sdk/releases/download/v4.12.1/Adjust_v4.12.1.unitypackage

**Comment by uerceg** [comment]
@okanulas 

Thanks, we're investigating and will ping you in here as soon as we can.

**Comment by uerceg** [comment]
@okanulas 

Can you give this SDK version a try and let us know if it solved your problem? We have just renamed `.unitypackage` to `.zip` so that Github allows it to be attached in here. Once you download it, just change extension from `.zip` back to `.unitypackage`. This is our next SDK update RC, so nothing official at the moment. Looking forward to hear from you on this.

Cheers

[Adjust_v4.12.2-RC1.zip](https://github.com/adjust/unity_sdk/files/1704175/Adjust_v4.12.2-RC1.zip)

**Comment by lallutin** [comment]
This is the same issue that happened to me and the RC1 did fix it for me.

**Comment by okanulas** [comment]
Thanks @uerceg. I'm going to try the package and share the results today.

**Comment by uerceg** [comment]
Awesome, thanks!

**Comment by okanulas** [comment]
@uerceg v4.12.2-RC1 is working on iOS 10 devices. Thank for your support.

**Comment by uerceg** [comment]
@okanulas Thanks for checking. Official 4.12.2 release will be live soon. Will update in here once it's live.

**Comment by uerceg** [comment]
@okanulas @lallutin  

This should now be fixed with latest v4.12.2 version: https://github.com/adjust/unity_sdk/releases/tag/v4.12.2

Feel free to reopen the issue if problem still persists with latest SDK version.

Thank you guys one more time for cooperation on this issue. 🍺 

Cheers
