### ISSUE TITLE
SDK Version

### ISSUE THREAD

**Issue by channingcorn** [adjust/unity_sdk#127]
Currently, there isn't a way to query the SDK Version without looking at source.
Can you change _sdkPrefix_ in each class from private to public, and then add a method to **Adjust.cs** like the following to allow access:

    public static string GetSdkPrefix()
    {
    	#if UNITY_IOS
    	return AdjustiOS.sdkPrefix;
    	#elif UNITY_ANDROID
    	return AdjustAndroid.sdkPrefix;
    	#elif (UNITY_WSA || UNITY_WP8)
    	return AdjustWindows.sdkPrefix;
    	#else
    	Debug.Log(errorMsgPlatform);
    	#endif
    }

**Comment by uerceg** [comment]
Hi @channingcorn 

`sdkPrefix` isn't something that was ever requested to be exposed so far. We will discuss this internally and hopefully consider adding this in some of our next releases. In general, SDK prefix is something that users should stay away from and don't try to change it on their own, but having in mind that you're just looking for a way to read it, I think it might be okay to add.

Will keep you posted in here.

**Comment by channingcorn** [comment]
@uerceg  The main reason is just a way to display or report the version of the SDK. sdkPrefix seemed like an option, but if you want to make a different method to display the current SDK version, I'm good with that too.

**Comment by uerceg** [comment]
Hi @channingcorn 

In our latest 4.17.0 release (https://github.com/adjust/unity_sdk/releases/tag/v4.17.0), we have added method `getSdkVersion()` on `Adjust` interface which should return to you full Unity SDK version string. For example in latest release: `unity4.17.0@ios4.17.1` on iOS or `unity4.17.0@android4.17.0` on Android platform.

We made it a bit broader than just prefix, so if you really need the prefix, you can split the string and get just the prefix part.

Hope this helps you a bit.

Cheers!
