### ISSUE TITLE
Install count not changed

### ISSUE THREAD

**Issue by AfifFaris** [adjust/unity_sdk#139]
Hi,

I tested my app in sandbox environment to check if the tracking works.

I got `Install Tracked` message in the log for both OS. These are the logs (I remove some of the logs with id or token information)

Android log
```
W/Adjust: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
I/Adjust: Google Play Services Advertising ID read correctly at start time
I/Adjust: Click tracked
I/Adjust: Install tracked
I/Unity: Session tracked successfully!
```

iOS log
```
[Adjust]w: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing
[Adjust]d: Adjust directory not present and will be created
[Adjust]v: AdjustIoAttribution file not found in "Application Support/Adjust" folder
[Adjust]v: AdjustIoAttribution file not found in Documents folder
[Adjust]v: AdjustIoActivityState file not found in "Application Support/Adjust" folder
[Adjust]v: AdjustIoActivityState file not found in Documents folder
[Adjust]v: AdjustSessionCallbackParameters file not found in "Application Support/Adjust" folder
[Adjust]v: AdjustSessionCallbackParameters file not found in Documents folder
[Adjust]v: AdjustSessionPartnerParameters file not found in "Application Support/Adjust" folder
[Adjust]v: AdjustSessionPartnerParameters file not found in Documents folder
[Adjust]v: Foreground timer configured to fire after 60.0 seconds of starting and cycles every 60.0 seconds
[Adjust]v: AdjustIoPackageQueue file not found in "Application Support/Adjust" folder
[Adjust]v: AdjustIoPackageQueue file not found in Documents folder
[Adjust]d: ADJUST_NO_IAD or TARGET_OS_TV not set
[Adjust]d: iAd framework successfully found in user's app
[Adjust]d: iAd with 2 tries to read v3
[Adjust]v: Foreground timer starting
[Adjust]v: Subsession start
[Adjust]v: Value found and read from the keychain v1 way
[Adjust]d: Added package 1 (session)
[Adjust]v: Path:      /session
[Adjust]v: ClientSdk: unity4.15.0@ios4.15.0
[Adjust]i: Install tracked
[Adjust]i: Click tracked
```

Somehow the Installs and Sessions count doesn't change. 

![count](https://user-images.githubusercontent.com/8552823/46398158-4e8c2d80-c72f-11e8-80c9-04446f2ce058.png)

I checked my device in test console and everything looks alright. I think the Install count won't change because I use sandbox environment instead of production, is this intended behavior? Do I miss something? 

![test](https://user-images.githubusercontent.com/8552823/46398165-55b33b80-c72f-11e8-8a65-3643d96040e1.png)

**Comment by uerceg** [comment]
Hi @AfifFaris 

Yes, that is intended behaviour. With SDK environments, we're trying to give you possibility to run tests in sandbox mode and see that later in the dashboard w/o mixing that traffic with your actual production traffic incoming from users that downloaded and used your app from app stores.

When you go to `Statistics` part in your dashboard and press filter icon, you can see on the bottom of the settings panel on the right checkbox called `Sandbox Mode`:

<img width="147" alt="screenshot 2018-10-03 at 11 16 05" src="https://user-images.githubusercontent.com/1741635/46401607-cccfdc00-c6fd-11e8-8695-fc35cbced9d5.png">

Once this checkbox is checked, you should see statistics in dashboard for all your sandbox traffic.

**Comment by AfifFaris** [comment]
Wow, I didn't realize there is sandbox mode button in filter icon. Took me half day figuring out whats wrong. 
Just some feedbacks, I think the sandbox mode placement is not quite intuitive and I can't find about it in the documentation. I think its easier to mention it somewhere in the docs.

Thank you for fast response. Its solved. 😄 
Cheers

**Comment by uerceg** [comment]
Glad it worked! And thanks for the feedback, will forward it. 🍺
