### ISSUE TITLE
MCC/MNC Warnings on App Launch

### ISSUE THREAD

**Issue by kromenak** [adjust/unity_sdk#140]
I'm testing our Unity SDK integration on Android devices, and I'm seeing this appear in the log when the app is launching on 2 of our 3 test devices:

```
W Adjust  : Couldn't receive networkOperator string to read MCC
W Adjust  : Couldn't receive networkOperator string to read MNC
W Adjust  : Couldn't receive networkOperator string to read MCC
W Adjust  : Couldn't receive networkOperator string to read MNC
```

My Android manifest does have "ACCESS_NETWORK_STATE", which the instructions state is required to read MMC and MNC.

I haven't been able to determine any significant configuration difference on the phone where these warnings don't appear. All are development devices for our company, none have SIM cards, all are connected to WiFi.

So, two questions/concerns:
1) What would cause the the above warnings?
2) Does this indicate that there is a problem with the SDK integration? Can I move forward with releasing the app like this, or would it cause reporting issues if this warning is appearing?

**Comment by uerceg** [comment]
Hi @kromenak 

1. Exactly the thing you described - lack of SIM card in your test devices.
2. There is most probably no issue at all with SDK integration and you can feel free to proceed with your app release if you have tested integration of SDK and that it does everything you expect it to do.

In case you have set up callbacks on dashboard and in there you expect `mcc`/`mnc` placeholders to be populated, then it might be good idea to test if MCC/MNC is being read properly while testing with device that has SIM card. In case you don't care for these values, then feel free to ignore these warnings.

Feel free to ping us in case you have any other questions.

Cheers

**Comment by uerceg** [comment]
Hi @kromenak 

Any update on this one?

Cheers

**Comment by kromenak** [comment]
@uerceg, thanks for checking in - based on your comment, I think we are OK on our end. Our app with Adjust integrated just launched a couple days ago!
