### ISSUE TITLE
Keeps adding install referrer to manifest.

### ISSUE THREAD

**Issue by feraligatr** [adjust/unity_sdk#144]
If there's a <receiver> defined in AndroidManifest.xml, which is not INSTALL_REFERRER, the build script will insert a new receiver every time.

https://github.com/adjust/unity_sdk/blob/4dddbd25decccef0dfe5e4128f143ce04f6ebe28/Assets/Editor/AdjustEditor.cs#L418

This code is absolutely wrong.
It should be:
`
                if (isThereAnyCustomBroadcastReiver)
                {
                    // If there's custom broadcast receiver, let's iterate on "receiver" attributes a bit more to see if it's ours.
                    foreach (XmlAttribute attribute in node.Attributes)
                    {
                        if (attribute.Value.Contains("com.adjust.sdk.AdjustReferrerReceiver"))
                        {
                            isUsedBroadcastReceiverOurs = true;
                        }
                    }
                    break;
                }
`

**Comment by uerceg** [comment]
Hi @feraligatr

Thanks for reporting and you are absolutely right. We already got this reported last week and you can expect patch update this week which will address this issue. 

Will keep you posted.

Cheers

**Comment by uerceg** [comment]
@feraligatr 

Should be fixed in v4.17.1 (https://github.com/adjust/unity_sdk/releases/tag/v4.17.1). In case issue is still there with latest version as well, please feel free to reopen the issue.

Cheers and thanks one more time for reporting! 🍺
