### ISSUE TITLE
How Can I see Unity SDK Logs?

### ISSUE THREAD

**Issue by ArmanAjdani** [adjust/unity_sdk#148]
Hi, I deployed adjust unity sdk, but when I run it it says that can not run sdk in Editor , How can I debug and see logs when I can't use sdk in Editor? I tested when Unity remote 5 but the answer was the same, How I can debug my implemntation?

**Comment by uerceg** [comment]
Hi @ArmanAjdani 

Our Unity SDK is not made to be run from Editor, only on physical devices or simulators/emulators. Logs are displayed on native level, so in case you are running your app on Android device/emulator, you can get LogCat output with `adb logcat -s Adjust` or if you're running your app on iOS device/simulator, you can check logs in Console app on OSX for example or any other way you're maybe using to obtain native iOS logs.

**Comment by ArmanAjdani** [comment]
OK, thank you for your answer, I didn't use debug becasue SDK works correctly now.

**Comment by uerceg** [comment]
In case you have any other concerns or questions feel free to shoot them in here and reopen the issue if needed. Cheers.
