### ISSUE TITLE
AndroidJNIHelper.debug == true

### ISSUE THREAD

**Issue by tony9002** [adjust/unity_sdk#154]
I updated to v4.18.2 using package from https://github.com/adjust/unity_sdk/releases and now ```AndroidJNIHelper.debug == true``` by default. It's annoying to have logs for every call to AndroidJNI for all modules (not only Adjust). Fix it please 🙏

**Comment by uerceg** [comment]
Hi @tony9002 

Thanks for letting us know. What do you suggest us to do about it? Should we set it to false in our package source code? Isn't this something you can turn off globally by setting it to false in your app?

Cheers

**Comment by tony9002** [comment]
Certainly I can and will change it in my app to prevent logs hell :) 

But I can't predict the time moment in which I should to change ```AndroidJNIHelper.debug``` to false. In MonoBehaviour.Awake() methods it is false. But then some time passes (Unity loads adjust library) and ```AndroidJNIHelper.debug``` gets true value.

> Should we set it to false in our package source code? 

It would be great! I think that 3rd party app shouldn't set global variables for debug purposes.

**Comment by uerceg** [comment]
But what's the scope of effect which will saying `AndroidJNIHelper.debug = false;` have if we do it from our plugin? Wouldn't that effect global app setting as well?

**Comment by tony9002** [comment]
AndroidJNIHelper is static object that defined in UnityEngine namspace. It effects all application. In my case I have AndroidJNI logs from facebook sdk and other 3rd party plugins.

**Comment by uerceg** [comment]
I am not sure this is something we want to do, since it seems like too intrusive action for any 3rd party plugin to perform. Global application settings unrelated to our plugin functionality is not something we want to mess with, since if we turn this off, we're probably gonna upset large number of users who don't expect our plugin (or any third party plugin) to mess around with this setting.

I am aware of the JNI logs which being printed out and also for us quite often they are beyond annoying, but maybe you can try filtering the JNI output you're checking at in LogCat in some way.

**Comment by tony9002** [comment]
1. In our app we are not using AndroidJNIHelper.debug at all.
2. I installed v4.18.2 and got ```AndroidJNIHelper.debug == true``` with numerous logs from AndroidJNI. It was the only change in app sources. Then I downgraded to 4.14.1, all logs disappeared and ```AndroidJNIHelper.debug == false```.

From my perspective - adjust sdk changes this setting to true during loading. And I think that it is wrong behaviour.

**Comment by uerceg** [comment]
Same thing with our plugin as you mentioned in 1 - we are not setting this to `true/false` anywhere in our code. Entire plugin source code is in this repo, feel free to check.

**Comment by tony9002** [comment]
Hmmm 🤔 Very strange. I'll try to check it in clean environment. 
Thank you for fast response!

**Comment by uerceg** [comment]
Closing this one since I don't think it's really related to our SDK. In case you have any further questions on this one, feel free to ask. Cheers.
