### ISSUE TITLE
iOS .a  use UIWebView APIs ?

### ISSUE THREAD

**Issue by Yosemite0915** [adjust/unity_sdk#158]
iOS .a  use UIWebView APIs ?

**Comment by uerceg** [comment]
Hi @Yosemite0915 

Are you asking about usage in native iOS app which uses `UIWebView` components or Unity app?

For usage of our iOS SDK inside of web views in native iOS apps, check [this guide](https://github.com/adjust/ios_sdk/blob/master/doc/english/web_views.md).

In case you have any further questions, feel free to shoot in here.

Cheers
