### ISSUE TITLE
Adjust fails to build in batch mode

### ISSUE THREAD

**Issue by fliperamma** [adjust/unity_sdk#172]
When building via batch-mode (Unity 2019.2.21f1) I get this error

> bitcode bundle could not be generated because `/Adjust/iOS/Test/AdjustTestLibrary.a(ATLUtilNetworking.o)` was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file `/Adjust/iOS/Test/AdjustTestLibrary.a` for architecture 

Similar or the same as [this](https://github.com/adjust/unity_sdk/issues/166). Is it ok to remove the whole iOS/Test folder?

**Comment by uerceg** [comment]
Hi @fliperamma 

Absolutely safe and feel free to do that. Just wondering if you can give us an answer to question I asked in [here](https://github.com/adjust/unity_sdk/issues/171#issuecomment-607167549)?

**Comment by fliperamma** [comment]
Thanks for your quick response @uerceg .. really appreciated
