### ISSUE TITLE
Can't Archive on Xcode 11.3.1

### ISSUE THREAD

**Issue by TeorikDeli** [adjust/unity_sdk#173]
Hi,

I think the SDK file for iOS is compiled with the newest Xcode (version 11.4) and now I can't archive on Xcode 11.3.1 because of that. I don't want to update my Xcode, because it is forcing me to update MacOS Catalina and I don't want to update my MacOS, because of the dropping 32-bit support (some apps I am using are still 32-bit =/ )

So, can you please recompile the SDK with an older Xcode?

**Comment by uerceg** [comment]
Hi @TeorikDeli 

Sorry for delay in replying. In theory, only part which is causing you trouble is native iOS .a library which is located in `Assets/Adjust/iOS/AdjustSdk.a`.

I have rebuilt it with Xcode 11: [AdjustSdk.a.zip](https://github.com/adjust/unity_sdk/files/4561833/AdjustSdk.a.zip)

Let us know if it worked for you.

Cheers

**Comment by uerceg** [comment]
In case you need any further assistance on this one, feel free to comment/reopen. Cheers.
