### ISSUE TITLE
[Android] AndroidManifest.xml merging issue

### ISSUE THREAD

**Issue by CodeMasterYi** [adjust/unity_sdk#178]
We find the file `AndroidManifest.xml` under `Assets/Plugins/Android` extended by `com.adjust.sdk.AdjustReferrerReceiver` node EVERYTIME after i build an android project!
NOW, we have 55 `com.adjust.sdk.AdjustReferrerReceiver`s in the file! =.=

Emmm... Why dont you use auto-merging by Unity?

**Comment by uerceg** [comment]
Hi @CodeMasterYi 

Which Unity SDK version are you using? We had one [PR](https://github.com/adjust/unity_sdk/pull/167) suggested which got merged in Unity SDK v4.20.1 which seems to me that it might address this issue so wondering if you maybe gave that or later version a shot.

Cheers

**Comment by CodeMasterYi** [comment]
HOW Can I find the version string?

**Comment by uerceg** [comment]
For example you can check [this line](https://github.com/adjust/unity_sdk/blob/master/Assets/Adjust/Android/AdjustAndroid.cs#L11) in your source files.

**Comment by CodeMasterYi** [comment]
`unity4.17.0`

**Comment by CodeMasterYi** [comment]
I will try the latest version then!

**Comment by uerceg** [comment]
Yeah, feel free to give some version after 4.20.1 a shot and hopefully your `AndroidManifest.xml` should not be overwritten anymore if there's no need for it. Let us know if overwriting stopped with latest version.

**Comment by CodeMasterYi** [comment]
It works well!
