### ISSUE TITLE
Bitcode error on archiving project

### ISSUE THREAD

**Issue by alihc** [adjust/unity_sdk#179]
I am using Max(appLovin) and Adjust unity v4.21.3 with facebook sdk. Build works fine if I just build it for device but getting bitcode error on archiving the build.

_"could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1103.0.32.59.0_0' Reader: '1100.0.33.17_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.17)' for architecture armv7"_

Unity version 2019.3.13
Xcode version 11.3.1

**Comment by uerceg** [comment]
Hi @alihc 

Sounds like same issue as reported in [here](https://github.com/adjust/unity_sdk/issues/173)?

Cheers

**Comment by alihc** [comment]
Thanks, that worked.
