### ISSUE TITLE
Event Logging Randomly

### ISSUE THREAD

**Issue by melih-veloxia** [adjust/unity_sdk#187]
We are using Unity 2019.2.21f1 with latest Adjust and Adjust Purchasing SDKs. 

Both the prices of the In-App-Purchases and the counts of the events are randomly logging to Adjust. 

Here is our In-App-Purchase script.

```
using com.adjust.sdk;
using com.adjust.sdk.purchase;

private string adjustToken = null;
private decimal adjustPrice = 0;
private string adjustCurrency = null;
private string adjustTransactionId = null;

...
    
public PurchaseProcessingResult ProcessPurchase(PurchaseEventArgs args)
{

    if (String.Equals(args.purchasedProduct.definition.id, houseofdiamonds, StringComparison.Ordinal))
    {
            // Do something in the game
            adjustToken = {OurEventToken};
            adjustPrice = args.purchasedProduct.metadata.localizedPrice;
            adjustCurrency = args.purchasedProduct.metadata.isoCurrencyCode;
    }

#if UNITY_IOS
    AdjustPurchase.VerifyPurchaseiOS(args.purchasedProduct.receipt, args.purchasedProduct.transactionID, args.purchasedProduct.definition.id, VerificationInfoDelegate);
#elif UNITY_ANDROID
    AdjustPurchase.VerifyPurchaseAndroid(args.purchasedProduct.definition.id, args.purchasedProduct.receipt, SystemInfo.deviceUniqueIdentifier, VerificationInfoDelegate);
#endif
    return PurchaseProcessingResult.Complete;
}

private void VerificationInfoDelegate(ADJPVerificationInfo verificationInfo)
{
    if (verificationInfo.VerificationState == ADJPVerificationState.ADJPVerificationStatePassed)
    {
        if(adjustToken != null && adjustPrice != 0 && adjustCurrency != null)
        {
            AdjustEvent adjustEvent = new AdjustEvent(adjustToken);
            adjustEvent.setRevenue((double)adjustPrice, adjustCurrency);
            adjustEvent.setTransactionId(adjustTransactionId);
            Adjust.trackEvent(adjustEvent);
        }
    }
    adjustToken = null;
    adjustPrice = 0;
    adjustCurrency = null;
    adjustTransactionId = null;
}
```

**Comment by ugi** [comment]
Hi @melih-veloxia 

Can you maybe explain what does "randomly logging" mean? Can you maybe share in here the logs and explain what is in there what you think it shouldn't be?

Cheers

**Comment by melih-veloxia** [comment]
Hey @ugi 

Here are some examples

For example from 7th of July to 10th of July here are the IAP events from Adjust dashboard and from stores (actual data):

**houseofdiamond** 
Adjust | _Count: 544 Revenue: $15,853.10_
Stores | _Count: 5 Revenue: $57.93_

**gemcollector**
Adjust | _Count: 89 Revenue: $2,849.67_
Stores | _Count: 113 Revenue: $434.41_

...

All the revenue events are going like these. When we contacted with support@adjust.com we have double checked the data together and the team also realized there is a problem. When we asked a raw data from them we have realized that there are random event logs with random revenue prices and random count. For example there are more than 10 events in an hour from a specific user for a specific event with different revenue parameters inside it. This is not a specific issue for a specific user or a specific platform or a specific product. We have checked our event functions, IAP script and related scripts hundred times but unable to find why the issue occurs.

**Comment by ugi** [comment]
Thanks for the detailed explanation. I will actually try to ping our support team to see if I can find the case and try to investigate this more in depth. Nothing much I can say for now since SDK integration seems to be just fine. Will keep you posted.

**Comment by melih-veloxia** [comment]
Hey @ugi 

Thank you for your effort. We are already on a mail cycle with the support team but the conversation is unable to go forward rather than comparing the data with App Store and Adjust.

**Comment by ugi** [comment]
Hey @melih-veloxia 

Unfortunately that's what probably needs to be done because the fact that your app got success response as an answer from PV SDK callback means that successfully verified is the state which Apple verification service returned to us for the given purchase which might not be the one which should have happened inside of your app. Because of that this kind of comparison would be useful so that we can isolate actual purchases for which you got paid by Apple and see what is "fishy" in those which managed to slip through verification process and start to prevent that. If you'd willing to assist in debugging, would be awesome.

Cheers

**Comment by ugi** [comment]
Hi @melih-veloxia 

Any update in here?

**Comment by melih-veloxia** [comment]
Hey @ugi 

We have solved our issue by enabling purchase verification module but this is just a workaround, not a proper solution. As far as I know, Adjust is still searching for the problem.
