### ISSUE TITLE
Release date for next Unity release including SKAdNetwork changes (iOS 14)

### ISSUE THREAD

**Issue by bhallionOhbibi** [adjust/unity_sdk#188]
Hello,

do you guys have any idea of the date for the next release ?
is it already in the pipe ?

Any info would be really appreciated :)

Cheers !

**Comment by ugi** [comment]
Hi @bhallionOhbibi 

It's already being worked on. Hopefully tomorrow. Will keep you posted.

Cheers

**Comment by bhallionOhbibi** [comment]
Hi @ugi 

Thanks for the quick response ! 

Have a nice day
