### ISSUE TITLE
Duplicate Symbols for architecture armv7

### ISSUE THREAD

**Issue by hbaInfinity** [adjust/unity_sdk#191]
Hey,

I was just upgrading the Adjust Unity SDK to the latest version in preparation for the iOS 14 changes, and once on the latest version, we seem to be getting duplicate symbol errors for the ADJUrlStrategy class on armv7 builds, which we were not getting on the older version (we upgraded from v4.20.0 to v4.23.0). 

Just to also note, we are using the latest version of the Adjust Purchase SDK in conjunction with this plugin (https://github.com/adjust/unity_purchase_sdk, using version 1.0.3), just in case that is what is causing this issue.

Has something changed inside the AdjustSdk.a file to cause this issue between updates?

Here is the current error our build system is reporting:

`duplicate symbol '_OBJC_CLASS_$_ADJUrlStrategy' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_METACLASS_$_ADJUrlStrategy' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._gdprUrlChoicesArray' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._subscriptionUrlChoicesArray' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._baseUrlChoicesArray' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._choiceIndex' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._startingChoiceIndex' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._wasLastAttemptSuccess' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenGdprUrl' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenSubscriptionUrl' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenBaseUrl' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._extraPath' in:
    /Jenkins/workspace/Build - iOS/Libraries/Adjust/iOS/AdjustSdk.a(ADJUrlStrategy-8702A38D30AAB0B9.o)
ld: 12 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any help would be appreciated.

Thanks!

**Comment by hbaInfinity** [comment]
Is there any thoughts or ideas on how to fix this issue?

**Comment by ugi** [comment]
Hi @hbaInfinity 

Hm, that's pretty weird. Having purchase SDK added shouldn't really change anything. It is a dummy attempt, but can you completely remove Adjust plugin from your app and re-import it?

**Comment by hbaInfinity** [comment]
Hey @ugi

I did think it could be something like that, but on the Unity side, I completely removed the Adjust plugin and reimported it again and compared the changes from before and after using our source control. We are also using a Jenkins build system, which does get completely wiped with each build, so I believe there isn't any old leftover artifacts from the previous version of Adjust.

It is weird that it is specifically failing on the ADJUrlStrategy symbols though, as other times I have experienced this issue, generally it is for shared libraries for different plugins.

**Comment by ugi** [comment]
Hey @hbaInfinity 

Just to make sure I understood well - reimport didn't help, you're still facing the issue? Also, which Unity and Xcode version are you using?

**Comment by hbaInfinity** [comment]
I haven't tried a second attempt at reimporting (just that the first attempt was a full removal of the plugin and reimporting it again, so it is something I can try again). 

Apart from that, we are using Unity 2018.3.7f1, and XCode 13.3.

**Comment by ugi** [comment]
I think we identified where the issue is, will try to follow up with patch update which fixes this during this week. Will keep you posted.

**Comment by hbaInfinity** [comment]
Hey @ugi ,

Thanks for looking into it, I'll wait until the patch is released and I will try it again with the changes!

**Comment by ugi** [comment]
Hi @hbaInfinity 

And thanks for the patience. We have just released [v4.23.1](https://github.com/adjust/unity_sdk/releases/tag/v4.23.1) update which should hopefully resolve this issue. Give it a shot and feel free to reopen/comment in case issue is still there.

Cheers
