### ISSUE TITLE
iOS gets stuck when calling requestTrackingAuthorizationWithCompletionHandler()

### ISSUE THREAD

**Issue by akapelon** [adjust/unity_sdk#192]
Hello,

I've implemented the steps here
for the new tracking authization dialog

https://github.com/adjust/unity_sdk#app-tracking-authorisation-wrapper

For both ios 12 and 14 it works as intended. And the call back gets called regardless of whether the dialog was displayed or not.

However for ios 13, the call back passed into Adjust.requestTrackingAuthorizationWithCompletionHandler() is never called and thus standard program operation does not continue.

Is there any suggestion or workaround for this?

**Comment by ugi** [comment]
Hi @akapelon 

And sorry for a bit delayed reply. Hm. In theory, best thing would be to invoke this API only on devices running iOS 14 and later. But still, it's odd that you're getting something back in iOS 12. Which value do you get back in callback when running it on iOS 12?

**Comment by akapelon** [comment]
Hello, i ended up calling this only on iOS 14, so yes, that solved my problem.
Unfortunately i don't know what value it was returning on iOS 14 as i was always ignoring the value.

Perhaps i will at some point in the future rerun it on an iOS 12 device but you can probably reproduce this yourselves locally just as easily (definitely sooner than me).
