### ISSUE TITLE
Can't add Google Play Services

### ISSUE THREAD

**Issue by andrey-melnikov** [adjust/unity_sdk#202]
Hello!
I am trying to add google play services as mentioned in the [tutorial](https://github.com/adjust/unity_sdk/blob/master/README.md#google-play-services). But my Android SDK structure is different from the structure displayed in the tutorial and I can't find a folder to import to Unity.
![image](https://user-images.githubusercontent.com/60381511/105911552-57f5de00-603b-11eb-8960-8ae7bc2a5aab.png)

As you can see there is no google-play-services_lib or  play-services-basement or  play-services-ads-identifier folder.
I am using SDK Manager and have downloaded everything (API level 30):
![image](https://user-images.githubusercontent.com/60381511/105910738-698ab600-603a-11eb-87bf-f9e7e084effe.png)

I have tried downgrading the SDK version but I still don't have the correct directory.

The second way to download a correct SDK also does not work:

> If you aren't using any tools with the Android SDK Manager, download the official standalone [Android SDK](https://developer.android.com/sdk/index.html#Other).

It just downloads the latest version of the android studio without SDK and there is no link to download SDK separately.

I hope you can help me with finding the correct folder to import into Unity.

**Comment by uerceg** [comment]
Hi @andrey-melnikov 

And sorry for a bit delay in response. Can you expand `google_play_services` folder and screenshot what's inside of it?

**Comment by andrey-melnikov** [comment]
> Hi @andrey-melnikov
> 
> And sorry for a bit delay in response. Can you expand `google_play_services` folder and screenshot what's inside of it?

Hello!
![image](https://user-images.githubusercontent.com/60381511/107337264-2bc26e80-6acb-11eb-8e7a-ae457dfed9f9.png)

**Comment by uerceg** [comment]
Hm. That's interesting. And probably good idea if we update our README to indicate probably easier way to do such thing. These Play Services artefacts are also hosted on Maven and in theory one can simply download them from there. So you can as well go to https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads-identifier and download `-ads-identifier` AAR file and use it for this purpose.
