### ISSUE TITLE
Adjust requestTrackingAuthorizationWithCompletionHandler doesn't show dialog in certain iOS version

### ISSUE THREAD

**Issue by psstevenchan** [adjust/unity_sdk#204]
Adjust v4.24.1
on iOS 14.2, it shows dialog.
on iOS 14.3, it doesn't show dialog.
on iOS 14.4, it shows dialog

**Comment by psstevenchan** [comment]
1. yes, I reinstall the app
2. yes, I am sure the toggle is ON before reinstall

There are only 2 devices with iOS 14.3 have problems, but other 2 devices with iOS 14.3 is working propertly

**Comment by uerceg** [comment]
@psstevenchan Sorry for delay in here. Did you manage to solve this one at the end? Was it maybe related to [this](https://9to5mac.com/2021/05/03/ios-14-5-1-release-changes/)?

**Comment by psstevenchan** [comment]
I do think it is my device issue.
