### ISSUE TITLE
How to update the SDK properly?

### ISSUE THREAD

**Issue by zenith-jacob** [adjust/unity_sdk#209]
Hello,

We're going to try to update the SDK to the latest one (4.26.1) from the one that we currently have (4.21.1).
What's the procedure? 

We're unable to find anything update-related in the docs :( 

If we just import the newest package and replace the files, would it work?

**Comment by uerceg** [comment]
Hi @zenith-jacob 

Yes, procedure is pretty much just to import new package and after import things should just be ready for you to use latest SDK version. Every SDK version we release within same major release (4.x.x) is always backwards compatible, so importing new SDK version will introduce no breaking API changes and leave all your SDK features you use functional.

In case you have any other questions, feel free to ping.

Cheers

**Comment by uerceg** [comment]
In case you have further questions on this topic, feel free to comment / reopen. Cheers!
