### ISSUE TITLE
requestTrackingAuthorizationWithCompletionHandler crash app

### ISSUE THREAD

**Issue by ttermeer-reboundcg** [adjust/unity_sdk#216]
Using requestTrackingAuthorizationWithCompletionHandler currently crash on iOS 14.5 Beta 7
`TCC, This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSUserTrackingUsageDescription key with a string value explaining to the user how the app uses this data.`

I easily fixed that on our game but I think either Adjust should add it in post process (and maybe allow to change the text within Adjust Settings) and/or it should be mentioned in the documentation.

**Comment by uerceg** [comment]
Hey @ttermeer-reboundcg 

Sorry for delay in replying and thank you for sharing this with us. We'll add this to our README, sounds like good idea to have such information in non native platforms READMEs. 👍

**Comment by uerceg** [comment]
As of Unity SDK v4.30.0 we have added possibility in inspector menu of Adjust prefab to enter value for `NSUserTrackingUsageDescription` which post build process will later pick up and make sure to be properly placed inside of the Xcode project. Thank you one more time for suggestion. Cheers.
