### ISSUE TITLE
I want to test the status of ATTrackingManagerAuthorizationStatusRestricted.

### ISSUE THREAD

**Issue by st0326s** [adjust/unity_sdk#222]
I saw the following site, but I can't figure out how to create this state on my iPhone.
What are the steps I should take to achieve this?

https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanagerauthorizationstatus/attrackingmanagerauthorizationstatusrestricted

//Development Environment
Unity2019.4.3f1

iPhone11
iOS Version 14.4.2

**Comment by uerceg** [comment]
Hi @st0326s 

I am not sure how can you put your device into restricted state. Some of the things which might be causing restricted state can be:

- If you have managed Apple ID (generated by some business / education institution).
- You have some profile installed on your device which restricts the access to ATT information.
- You didn't set the age on your Apple ID profile or you did, but it's maybe under 18 years old.

Seems like age trick might be the easiest to try, but like said, not really sure if it works.

In case you end up being able to force state of your iOS device to restricted mode, would be great if you can share the story about how you managed to do that.

Cheers
