### ISSUE TITLE
TrackAdRevenue uses wrong Environment

### ISSUE THREAD

**Issue by BennXYZ** [adjust/unity_sdk#231]
Hey.

We have set up TrackAdRevenue for our App, tracking our AdMob-Revenue and everything seems to work just fine. However, the AdRevenue is always tracked in our Production-Environment, despite the client definitely being set to Sandbox.

Is this intended or is there a way to set the Environment for the TrackAdRevenue-Function?

Note: We're setting the Adjust-Environment via Code instead of the CheckBox, which is actually required for some of our builds.

**Comment by uerceg** [comment]
Hey @BennXYZ 

And please sorry for delay in replying to this one. Just wanted to double check first if you maybe managed to resolve this one down the road or is this still an issue for you?

**Comment by BennXYZ** [comment]
We couldn't find a solution for this one back in October, so we just don't track our TrackAdRevenue if the adjust environment is set to sandbox.
I don't know if this issue has been solved with a new release.

**Comment by uerceg** [comment]
In theory, it shouldn't even be happening in previous versions (which you used when initially giving this a shot). I am not sure if you are still interested in using this feature. I will close this ticket for now, but in case you are still interested in the feature, please feel free to give it a shot again with latest SDK version and in case you still encounter the same issue, feel free to comment / reopen and we'll take a look. Sorry one more time for delay. Cheers.
