### ISSUE TITLE
When is the next update?

### ISSUE THREAD

**Issue by ilterbilguven** [adjust/unity_sdk#236]
iOS and Android SDKs are ahead of Unity SDK. We are waiting for "Added support for AdMost ad revenue source.". When will Adjust update Unity SDK?

**Comment by uerceg** [comment]
Hey @ilterbilguven 

We're aiming to have Unity SDK update with AdMost ad revenue tracking shipped in next few days. Will keep you posted.

**Comment by uerceg** [comment]
Oh, sorry for forgetting to ping in here. Cheers!
