### ISSUE TITLE
Assets/Adjust/Unity/AdjustUtils.cs(218,56): error CS0246: The type or namespace name 'JSONClass' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by namini40** [adjust/unity_sdk#250]
Hi there!
I added  [`Adjust Unity SDK v4.31.0`](https://github.com/adjust/unity_sdk/releases/tag/v4.31.0). after importing the package following error keeps showing.
```
Assets/Adjust/Unity/AdjustUtils.cs(218,56): error CS0246: The type or namespace name 'JSONClass' could not be found (are you missing a using directive or an assembly reference?)
```
which is referring to `AdjustUtils.cs` file and the method input `JSONClass`:
```cs

        public static void WriteJsonResponseDictionary(JSONClass jsonObject, Dictionary<string, object> output)
        {
          ...
```

also 
error:
```
Assets/Adjust/Unity/AdjustUtils.cs(194,44): error CS0246: The type or namespace name 'JSONNode' could not be found (are you missing a using directive or an assembly reference?)
```
at:
```cs
        public static String GetJsonString(JSONNode node, string key)
        {
         ...
```
I can not build my project.

Xcode v13.3
Macbook air 2020 (macOS Monterey Version 12.5)
Unity 2021.3.0f1

Thank you!

**Comment by uerceg** [comment]
Hey @namini40,

Thank you for reporting this. We'll take a look on our end and keep you posted.

**Comment by uerceg** [comment]
Not sure why are you facing this. I have just tried to import Adjust v4.31.0 unity package into a Unity app and place where that missing type should be located is also being added as part of the package. Do you have this file added to your app as well?
![Screenshot 2022-08-22 at 09 22 06](https://user-images.githubusercontent.com/1741635/185863843-bc3607ea-436a-4279-a1ee-d21be2cb6236.png)

**Comment by namini40** [comment]
thanks @uerceg, I'm pretty sure i did it. how ever im going to make sure and get back to you, thanks for quick response

**Comment by namini40** [comment]
hi @uerceg . you were right. I accidentally dropped one file from importing and didn't noticed. thanks again 🍻
