### ISSUE TITLE
[Question] INSTALL_PACKAGES permission required always?

### ISSUE THREAD

**Issue by novemberi** [adjust/unity_sdk#268]
I'm now trying to support new platform Google Play Games Beta. That platform doesn't allow INSTALL_PACKAGES permission. So maybe I should remove that permission on that platform build. Is that should be need always? How can I use Adjust SDK even though remove that permission?

**Comment by uerceg** [comment]
Hi @novemberi,

Adjust SDK doesn't require that permission at all. If you check Adjust prefab settings in the inspector menu, you'll see what permissions is Adjust SDK letting you to pick whether you want to add them to your app or not (https://github.com/adjust/unity_sdk/blob/master/Assets/Adjust/Editor/AdjustSettingsEditor.cs#L74-L89). But none of those is `android.permission.INSTALL_PACKAGES` permission.

I am not sure whether removal of that permission from your app might be a deal breaker for some other libraries you're using in your app, but it should definitely not affect any functionality of the Adjust SDK.

In case you have any further questions, feel free to ping.

Cheers

**Comment by novemberi** [comment]
Thank you!
