### ISSUE TITLE
Move unity_sdk/Assets/Plugins/iOS to Editor/Adjust

### ISSUE THREAD

**Issue by yuewah** [adjust/unity_sdk#27]
I see most of the unity3d ios plugins (especially prime31 plugins) will put the source code to Editor folder, then copy to xcode project in PostProcessBuild.

**Comment by nonelse** [comment]
Thanks, will look into using this method for v4. If you have any other reference it's appreciated

**Comment by uerceg** [comment]
Folder structure is updated for Unity 4.x.x and Unity 5.x.x since v4 of our SDK. @yuewah feel free to reopen this issue if you have some objections to current structure.
