### ISSUE TITLE
Build error on iOS after upgrading to 4.33.1

### ISSUE THREAD

**Issue by rbyjoswald** [adjust/unity_sdk#271]
Hello. After upgrading the SDK to 4.33.1 I'm getting build errors on iOS.

temp20230724-3043-1mt9ktu/Libraries/Adjust/iOS/AdjustUnity.mm:850:26: no visible @interface for 'AdjustTestOptions' declares the selector 'setIAdFrameworkEnabled:'
[testOptions setIAdFrameworkEnabled:(BOOL)iAdFrameworkEnabled];

I'm building using UCB with Xcode 14.1.0 & Unity 2021.3.19f1. Any idea how to solve this?

**Comment by rbyjoswald** [comment]
Something to do with the iAdFrameworkEnabled property being removed from Adjust.h in this commit
https://github.com/adjust/unity_sdk/commit/63e2726d4872ca719e64b176f29511b6ea3a3f2c
but still being used at the bottom of AdjustUnity.mm?
https://github.com/adjust/unity_sdk/blob/master/Assets/Adjust/iOS/AdjustUnity.mm

**Comment by uerceg** [comment]
Yup, that's pretty much how it appears, even though still wired how did it slip into this release. We'll try to reproduce this on our end and if we reproduce it (seems like we should be able to), we'll ship the patch update as soon as possible.

**Comment by uerceg** [comment]
Hi @rbyjoswald,

We have just released [v4.33.2](https://github.com/adjust/unity_sdk/releases/tag/v4.33.2) where we tried to address this issue. If you can try it out and let us know if it fixes your issue, that would be great.

Looking forward to hearing back from you.

Cheers

**Comment by rbyjoswald** [comment]
Thanks, it's building again with 4.33.2!
