### ISSUE TITLE
Xcode Build Fail l(d: Undefined symbols: , error: linker command failed with exit code 1 (use -v to see invocation))

### ISSUE THREAD

**Issue by SeoWo0** [adjust/unity_sdk#293]
<img width="875" alt="스크린샷 2024-04-18 오전 10 21 22" src="https://github.com/adjust/unity_sdk/assets/97532242/ae8b0b38-ebf6-4c53-903e-2affa11ab3bc">

Everything was done according to the SDK as written in the picture above.

Adjust_v4.38.0.unitypackage in Unity
I built it by adding only

In xcode, all necessary frameworks have been added to TARGETS -> UnityFrameWork -> Build Phase -> Link Binary with Libraries.

After setting the above, if you build with Archive in xcode,

ld: Undefined symbols:
  _ADJDataResidencyEU, referenced from:
      __AdjustLaunchApp in AdjustUnity.o
  _ADJDataResidencyTR, referenced from:
      __AdjustLaunchApp in AdjustUnity.o
  _ADJDataResidencyUS, referenced from:
      __AdjustLaunchApp in AdjustUnity.o
  _ADJUrlStrategyChina, referenced from:
      __AdjustLaunchApp in AdjustUnity.o
  _ADJUrlStrategyCn, referenced from:
      __AdjustLaunchApp in AdjustUnity.o
  _ADJUrlStrategyCnOnly, referenced from:
      __AdjustLaunchApp in AdjustUnity.o
  _ADJUrlStrategyIndia, referenced from:
      __AdjustLaunchApp in AdjustUnity.o
  _OBJC_CLASS_$_ADJAdRevenue, referenced from:
       in AdjustUnity.o
  _OBJC_CLASS_$_ADJConfig, referenced from:
       in AdjustUnity.o
  _OBJC_CLASS_$_ADJEvent, referenced from:
       in AdjustUnity.o
  _OBJC_CLASS_$_ADJPurchase, referenced from:
       in AdjustUnity.o
  _OBJC_CLASS_$_ADJSubscription, referenced from:
       in AdjustUnity.o
  _OBJC_CLASS_$_ADJThirdPartySharing, referenced from:
       in AdjustUnity.o
  _OBJC_CLASS_$_Adjust, referenced from:
       in AdjustUnity.o
  _OBJC_CLASS_$_AdjustTestOptions, referenced from:
       in AdjustUnity.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The build fails after the above error log. Is there anything else I need to do?

**Comment by SeoWo0** [comment]
solved it
Some parts of the .a file and ios sdk were missing.
thank you

**Comment by uerceg** [comment]
Hi @SeoWo0,

Thank you for the update. For future reference, in case anyone else stumbles upon the same issue, can you explain how exactly did you solve the issue?

**Comment by SeoWo0** [comment]
I first added the Adjust unity package to Android and then moved it to the Adjust folder in iOS, but the above bug persisted.

The issue was resolved by re-importing the Adjust SDK Unity package and updating the missing .a file and the rest of the SDK.

I'm not sure why the .a file and the rest of the SDK were missing from the adjuist folder on iOS.

**Comment by uerceg** [comment]
Huh, interesting. But thank you very much for the follow up and explanation how did you solve the issue. Cheers!

**Comment by SeoWo0** [comment]
Thanks!
