### ISSUE TITLE
OpenUPM couldn't publish updates after 5.0.2

### ISSUE THREAD

**Issue by ilterbilguven** [adjust/unity_sdk#314]
I can't update Adjust using OpenUPM due to errors while cloning the repository:
https://openupm.com/packages/com.adjust.sdk/?subPage=pipelines 

OpenUPM clones the repo and prepares the release after that. But [sdk @ cfa3d1a](https://github.com/adjust/ios_sdk/tree/cfa3d1a684a095fd01415b4000df367f3e96ad55) is missing. Thus, it couldn't continue.

This is important for devs using OpenUPM.

**Comment by uerceg** [comment]
Hi @ilterbilguven,

Very interesting. Thank you for reporting this. Do you know if there's maybe some OpenUPM `.gitignore` equivalent where one can specify what should OpenUPM ignore during the attempt to clone the repo?

**Comment by ilterbilguven** [comment]
Unfortunately, no.

It has some settings like that: 
<img width="541" alt="image" src="https://github.com/user-attachments/assets/55c2877b-5961-46a3-bee2-5df7f2976a62">

The repo must be cloneable incl. submodules.

**Comment by uerceg** [comment]
I think that the reason why it's currently failing is just because we left that submodule reference to point to a private repo. Let me quickly switch it back to the public one to see if that's gonna do the trick for you. Will ping in here in a bit after that's done.

**Comment by uerceg** [comment]
@ilterbilguven Whenever you manage to, give it another try and looking forward to hear if anything has changed now that the submodules are aiming at the public repos.

**Comment by uerceg** [comment]
👍 Then, it might take a bit to do that, but it will be part of the next release.

**Comment by uerceg** [comment]
Hello @ilterbilguven,

If you can give [v5.0.5](https://github.com/adjust/unity_sdk/releases/tag/v5.0.5) a shot to check if issue might have been resolved with it, that'd be great.

Looking forward to hearing back from you.

**Comment by ilterbilguven** [comment]
Hi, @uerceg 
[It is working now.](https://openupm.com/packages/com.adjust.sdk/?subPage=pipelines) Thanks.
