### ISSUE TITLE
Issue with Adjust SDK version 5.0.1+ - Missing Dependency

### ISSUE THREAD

**Issue by KiritoMC03** [adjust/unity_sdk#322]
Hello!

I have an error while building Unity project for Android platform:
```
* What went wrong:
Execution failed for task ':unityLibrary:generateReleaseRFile'.
> Could not resolve all files for configuration ':unityLibrary:releaseCompileClasspath'.
   > Failed to transform adjust-android-signature-3.35.1.aar (com.adjust.signature:adjust-android-signature:3.35.1) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find adjust-android-signature-3.35.1.aar (com.adjust.signature:adjust-android-signature:3.35.1).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/adjust/signature/adjust-android-signature/3.35.1/adjust-android-signature-3.35.1.aar
            https://repo.maven.apache.org/maven2/com/adjust/signature/adjust-android-signature/3.35.1/adjust-android-signature-3.35.1.jar
```

Steps to Reproduce:
Add Adjust SDK version 5.0.1+ to the project dependencies.
Attempt to build project for android platform
The error is thrown during the dependency resolution process.

Expected Behavior:
-The SDK should resolve all dependencies correctly and build without errors.

Actual Behavior:
The build fails due to the missing artifact.

**Same Android SDK issue**: https://github.com/adjust/android_sdk/issues/625

**Comment by uerceg** [comment]
Hey @KiritoMC03,

`adjust-android-signature-3.35.2` update should be released with the fix. If you say to EDM4U JAR resolver to resolve the dependencies, is it picking it up?

**Comment by uerceg** [comment]
Also, can you give [v5.0.6](https://github.com/adjust/unity_sdk/releases/tag/v5.0.6) a shot and let us know if it solves this issue for you or not? Looking forward to hearing back from you.

**Comment by KiritoMC03** [comment]
Hi!
Yes, the [v5.0.6](https://github.com/adjust/unity_sdk/releases/tag/v5.0.6) update has fixed our issue when building Android.
Thanks for the quick fix!

**Comment by uerceg** [comment]
Great! Thank you very much for letting us know and apologies one more time for the inconvenience from yesterday.
