### ISSUE TITLE
Use BuildTarget instead of #defines

### ISSUE THREAD

**Issue by b0rje** [adjust/unity_sdk#36]
When a unity build is executed in batchmode, it is not safe to rely on UNITY_IOS or UNITY_ANDROID defines in the [PostProcessBuild] function (thats why the target platform is passed as argument). The PostProcessBuild runs in the environment in which it is started, not nessessarily in the environemt it will build for (this is determined in the BuildPipeline.BuildPlayer(..) call). I suggest using the BuildTarget argument in the Postprocessing function.

**Comment by aphexyuri** [comment]
This is true - we ran into the same issue and I had to change to using 'target'. I should also add that I'm only seeing this with Adjust (we integrate with many other SDK). I to currentplatform checks any numerous places, and values are always iOS, but the #if UNITY_IPHONE never gets executed - very weird behaviour

**Comment by wellle** [comment]
Thanks for the suggestion, we'll do that in the upcoming update :+1:

**Comment by uerceg** [comment]
@b0rje @aphexyuri Sorry for delay in solving this issue, planning to add it to next release. I see what you mean, but do you have advice how to detect platform for `MenuItem` entries in `AdjustEditor.cs`?

**Comment by b0rje** [comment]
Hi @uerceg,
In the MenuItems its perfectly fine to use #if. But for everthing thats is executed during a buildprocess (especially when running unity in batchmode for creating a build as we do on our buildservers) you should use the BuildTarget (which is passed as a parameter in the OnPostProcess methods). This is the source as it worked for us:

[AdjustEditor.cs.zip](https://github.com/adjust/unity_sdk/files/323175/AdjustEditor.cs.zip)

**Comment by uerceg** [comment]
Hi @b0rje 

And thank you very much for this example, we'll probably add it to our next release. Will ping in here once it's live.

Cheers!

**Comment by uerceg** [comment]
Added to current PR, will be live soon.

For reference: https://github.com/adjust/unity_sdk/pull/69/commits/e6cbd18128449f6c75cf5d02c98077cbb70b82b7

**Comment by uerceg** [comment]
Included in latest `v4.7.0`: https://github.com/adjust/unity_sdk/releases/tag/v4.7.0

Thank you one more time for suggestion.

Cheers!
