### ISSUE TITLE
Android project does not build on windows

### ISSUE THREAD

**Issue by tenpn** [adjust/unity_sdk#38]
AdjustEditor starts a process with PostprocessBuildPlayer_AdjustPostBuildAndroid as the filename. On OSX this works because the OS can work out how to run that file, but Windows has no idea how to do that. It can only work if you pass PostprocessBuildPlayer_AdjustPostBuildAndroid as a parameter to the python executable. 

Please make this build on windows as well.

**Comment by nonelse** [comment]
We didn't try yet to build the android target in a Windows machine. I didn't understand your suggestion to pass the name of the script `PostprocessBuildPlayer_AdjustPostBuildAndroid` as a parameter to the python executable, that is the script.
Can you clarify this? Or even better, provide a PR with the needed changes so we can test it and merge it?
Thank you!

**Comment by tenpn** [comment]
Hey,

Here's a stackoverflow answer with more details: http://stackoverflow.com/questions/11779143/run-a-python-script-from-c-sharp. 

As a start I'd document in your readme that android builds on windows are not yet supported.

**Comment by wellle** [comment]
@tenpn: We'll check the windows compatibility for version 4, thank you :+1:

**Comment by tenpn** [comment]
what's the timescale for v4?

**Comment by wellle** [comment]
Months.

**Comment by uerceg** [comment]
@tenpn Are you still facing this issue with latest Adjust SDK for unity? Thanks in advance for answer.

**Comment by tenpn** [comment]
We dropped your service, so I can't tell you. :P

**Comment by uerceg** [comment]
Sorry to hear that. Anyway, this thing should work w/o any issues now, thus closing the issue. Hope you'll be back to our service. :)
