### ISSUE TITLE
Response delegate never gives session callback

### ISSUE THREAD

**Issue by tenpn** [adjust/unity_sdk#39]
I want to capture the session event with a response delegate, but I never seem to get the data. Here's my setup:

- uninstall game from android device
- re-install and launch game
- on boot, Adjust prefab self-inits
- later, I use Adjust.setResponseDelegate() to set a callback
- I get callbacks for revenue events, but no session callback

I hacked Adjust.runResponseDelegate() to tell me when any event comes in, in case I'm not subscribing in time for the callback, but there never seems to be an session event.

**Comment by wellle** [comment]
Try closing the app for at least thirty minutes and open it again afterwards without reinstalling. You should see a callback then.

But please note that this callback will be removed with v4. Instead there will only be a callback which will be called when the attribution changed.

**Comment by tenpn** [comment]
What I'm really trying to get is a local code callback with the network and tracker names on install. Is there another way to do that?

**Comment by tenpn** [comment]
(I did indeed get the session event after following your 30min hint. You can close this if you like.)

**Comment by wellle** [comment]
I guess this is the same race condition reported in https://github.com/adjust/adobe_air_sdk/issues/11. Luckily for you, the Unity SDK will be the next one we upgrade. After that you have exactly the callback you're asking for and it will always be called (exactly when the attribution changes, including the very first time).
