### ISSUE TITLE
Large size of Adjust.a

### ISSUE THREAD

**Issue by thaker** [adjust/unity_sdk#41]
The Adjust.a object file is really large and takes up 3.4MB. This is unacceptable for most apps given iOS requires your app size to be under 100MB.  One User Acquisition provider can't have an object file, not counting other files, that takes up at least 3.4% of your build.  That is quite large.

Code can't make up that size so there must be other files in that object file.  Is there an alternative to using this .a file?

Thanks so much!

**Comment by nonelse** [comment]
Hi @thaker, thanks for the feedback
The size of the library does not reflect on the size of the final app.
The library contains the binary for different architectures, that is why is large.
When it's actually used in one of the architectures, the rest are not linked to the final app.
In the example GUI app, the difference of having the adjust SDK or not was about 300kb, something similar to our native iOs SDK.
Did you find a different value on your side?

**Comment by uerceg** [comment]
Hi @thaker 

Any updates on this issue you had?

**Comment by thaker** [comment]
This issue is no longer relevant. Thanks for responding.

**Comment by uerceg** [comment]
:+1:
