### ISSUE TITLE
Unity - SimpleJSON namspace

### ISSUE THREAD

**Issue by aphexyuri** [adjust/unity_sdk#42]
I ran into a scenario where an existing project already used SimpleJson resulting in some conflicts. Is there a better way for Adjust to include a separate name-spaced SimpleJSON?

**Comment by uerceg** [comment]
@aphexyuri Thanks for your message.

We're gonna check how to solve this to avoid these kinds of conflicts.

**Comment by uerceg** [comment]
Added to `v4.6.0`: https://github.com/adjust/unity_sdk/releases/tag/v4.6.0

For reference: https://github.com/adjust/unity_sdk/pull/66/commits/cd822bb269de90aade4553b8a2c809f48397d658

Cheers
