### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by spacetraveller** [adjust/unity_sdk#43]
In Unity, the AdjustEvent does not appear to exist.

The Adjust.trackEvent() event appears to take parameters of:
`    (string eventToken, dictionary<string,string> parameters=null)`

Could you please clarify the documentation - the AdjustEvent object does not appear to exist in the Adjust Unity library.

**Comment by uerceg** [comment]
Hi @spacetraveller 

If your `Adjust.trackEvent` method gets those parameters, then you are probably still using v3.x.x of our Unity SDK. In `Adjust.cs` class of Unity SDK v3.4.4 declaration of this method looks like this:

```csharp
public static void trackEvent(string eventToken, Dictionary<string,string> parameters = null)
```

Current documentation on repository is written for Unity SDK v4.0.0 which we recently released. In there, you have [`AdjustEvent` class](https://github.com/adjust/unity_sdk/blob/master/Assets/Adjust/Unity/AdjustEvent.cs).

And `Adjust.trackEvent` method now has this declaration:

```csharp
public static void trackEvent (AdjustEvent adjustEvent)
```

If you plan to migrate from Unity SDK v3.x.x to our latest v4.0.0, make sure to read `Migration Guide` which can be found on [this link](https://github.com/adjust/unity_sdk/blob/master/doc/migrate.md).

If you have more questions or doubts, feel free to contact us.

**Comment by uerceg** [comment]
Feel free to reopen this issue if you are still facing difficulties.
