### ISSUE TITLE
Build iOS Project Error with UNITY4.6.6 + Adjust3.4.3

### ISSUE THREAD

**Issue by auycro** [adjust/unity_sdk#44]
I installed Unity5.1.1 then reinstall with Unity4.6.6.
After that i got this error when build iOS project. 

Could you help me figure this out?
Thank you in advance.
```
MacPro:Editor sps$ ./PostprocessBuildPlayer_AdjustPostBuildiOS /sps/iOSBuild/
Traceback (most recent call last):
  File "./PostprocessBuildPlayer_AdjustPostBuildiOS", line 122, in <module>
    main()
  File "./PostprocessBuildPlayer_AdjustPostBuildiOS", line 28, in main
    edit_unity_xcode_project(LogFunc, unity_xcode_project_path, framework_path)
  File "./PostprocessBuildPlayer_AdjustPostBuildiOS", line 55, in edit_unity_xcode_project
    unity_XcodeProject = XcodeProject.Load(unity_xcode_project_path)
  File "/sps/UnityApp/Assets/Editor/mod_pbxproj.py", line 1288, in Load
    tree = json.loads(jsonStr)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 1 column 1191 (char 1190)
```

**Comment by uerceg** [comment]
Hi @auycro 

Were you already opening and building your project with out SDK v3.4.3 successfully with Unity 5.1.1 before you started using Unity 4.6.6?

**Comment by auycro** [comment]
Hi @uerceg 

I think I opened the project with Unity5 once, but I didn't built it. Then I reverse all items in the Unity Project folder to the version back to Unity4.

**Comment by uerceg** [comment]
I have just tested this scenario.

1. I have opened our sample app with `Unity 5.1.1`. (so project files and all other files were generated / edited by Unity 5.1.1 which always make some compatibility problems when trying to open it afterwards with lower version of Unity)
2. I have opened our sample with `Unity 4.6.6`.
3. First message which popped up was this:
![screen shot 2015-06-25 at 11 36 32](https://cloud.githubusercontent.com/assets/1741635/8351716/b3346284-1b2f-11e5-8ea5-a9b30ad42e9e.png)
4. After I continued, another message popped up:
![screen shot 2015-06-25 at 11 36 44](https://cloud.githubusercontent.com/assets/1741635/8351734/cbd26138-1b2f-11e5-8544-8933bf4ba217.png)
5. I have loaded default layout and opened project in `Unity 4.6.6`.

I have successfully built it and post build script has been successfully executed, so seems like I can't reproduce situation you are facing.

Next two things maybe to check:

1. Do you have `python 2.7 or higher` installed on your computer? If not, install it.
2. Do post build python scripts have executable permissions? If not, make them executable.

**Comment by auycro** [comment]
Thank you for your suggestion. @uerceg 

I checked on python version and permissions as your suggestion. I still got the same error. Then, I'm copy this project to another pc. This project can be built. 
So, I remove all Unity components(Application,Preferences,Logs,etc.) and installed it again. Now, it's working again.

**Comment by uerceg** [comment]
@auycro Thanks for the update. Glad it worked.

Cheers
