### ISSUE TITLE
Multiple instances of the prefab in Unity Editor

### ISSUE THREAD

**Issue by PNordlund71** [adjust/unity_sdk#49]
In Unity Editor, I stick the Adjust prefab on a scene that loads other scenes in our game. This main scene gets loaded multiple times during gameplay. When running in Unity Editor, multiple instances of the Adjust plugin are created. Considering making the Adjust script a singleton.

**Comment by uerceg** [comment]
@PNordlund71 are you still facing this issue and if yes, can you please tell me which Adjust SDK version are you using? Thank you in advance and sorry for delayed answer.

**Comment by PNordlund71** [comment]
unity4.1.0

This happens because we have the Adjust prefab in a scene that gets loaded every time when changing between different scenes in our game. The Adjust.cs script should be a "singleton" type - or check in Awake if an instance is already running.

**Comment by uerceg** [comment]
Hi @PNordlund71 

We're planning to add following lines to `Awake` method, would this solve your issue: https://github.com/adjust/unity_sdk/blob/log_delegate/Assets/Adjust/Adjust.cs#L28

Cheers

**Comment by uerceg** [comment]
@PNordlund71 We have fixed this in our latest release. From now on, we are always checking Adjust instance in `Awake` method, like you have suggested. Thank you once again for reporting and suggestions.

Commit: https://github.com/adjust/unity_sdk/commit/4d81017e2de2380bce8ffe76d93eef315f7ff20d
PR: https://github.com/adjust/unity_sdk/pull/58
Release: https://github.com/adjust/unity_sdk/releases/tag/v4.1.1
