### ISSUE TITLE
Expose Adjust Id

### ISSUE THREAD

**Issue by Disturbing** [adjust/unity_sdk#51]
Can you expose the adjust id so we can manually map our players to callback data?

**Comment by uerceg** [comment]
@Disturbing We will internally discuss this request and will let you know as soon as possible.

**Comment by Disturbing** [comment]
@uerceg  Thanks :)!

**Comment by uerceg** [comment]
Just a short update on this issue. We're preparing native SDK updates in beginning of 2016 which will enable us to provide you with this info. As soon as we update native ones, we'll start with update of non-native SDKs and bring that functionality to Unity SDK as well.

Cheers

**Comment by Disturbing** [comment]
Thanks for the update @uerceg -

Do we have an ETA ( maybe a month ) I can depend on?  I'm still looking forward to seeing this ticket come to fruition.

**Comment by uerceg** [comment]
Hi @Disturbing 

Unfortunately not any accurate ETA. You can follow our native SDKs PRs for iOS and Android:

https://github.com/adjust/ios_sdk/pull/150
https://github.com/adjust/android_sdk/pull/161

Once those are merged, we'll start with Unity SDK upgrade. We're aiming to have native SDKs updated this week, hopefully at latest point next week. So, maybe a month is kinda realistic promise for Unity SDK update, but not a promise. We'll give our best to update it as soon as possible. :)

**Comment by Disturbing** [comment]
Cool,

An easier request would be to expose the GPS and IDFA that you guys are getting / storing in the callbacks of installs / clicks, etc.

Reason being is all the methods I've tried to map my database -> callbacks coming from adjust, i could not get exact ID's to match for both google and apple.  That's all I need to solve, simply exposing all ids that you guys store for external use / us to reference would be great so we're all on the same page, literally :).

**Comment by wellle** [comment]
To match our data to yours you should use our `adid`. Everything else might lead to discrepancies.

**Comment by Disturbing** [comment]
Agreed - just waiting for the merge so the Unity SDK can expose the adid unless it's hidden somewhere already :)?

Got tons of data waiting to be linked!

**Comment by uerceg** [comment]
At the moment, it's actually hidden, except of course in verbose logs. :)

As soon as we update native SDKs, we'll update Unity SDK with those changes.

**Comment by Disturbing** [comment]
Otay.. waiting on it! :+1:

**Comment by nonelse** [comment]
Thanks for the reminder. You can check in the guide how to access the device ids https://github.com/adjust/unity_sdk#12-device-ids

**Comment by Disturbing** [comment]
Works, thanks a ton folks!
