### ISSUE TITLE
can't pass WACK 

### ISSUE THREAD

**Issue by BloodJohn** [adjust/unity_sdk#56]
after build Unity & WSA project - WACK failed on AdjustUnityWS.dll

Error Found: The debug configuration test detected the following errors:
The binary AdjustUnityWS.dll is built in debug mode.

**Comment by uerceg** [comment]
@BloodJohn Thank you for reporting, we'll check this issue and answer you as soon as possible.

**Comment by uerceg** [comment]
@BloodJohn We have fixed this now. Feel free to reopen issue if you face any more issues.

PR: https://github.com/adjust/unity_sdk/pull/58
Release: https://github.com/adjust/unity_sdk/releases/tag/v4.1.1
