### ISSUE TITLE
Error when archiving with bitcode

### ISSUE THREAD

**Issue by epsmarkh** [adjust/unity_sdk#62]
Unity 5.3.2p2
Xcode 7.2.1
Adjust_v4.1.2_Unity_5

When compiling with bitcode enabled, compile and run works fine. However compile and run only targets the connected architecture and archive builds fail with the following error:

ld: bitcode bundle could not be generated because '/Users/unitybuild/adjusttest/iOS/Libraries/Adjust/iOS/AdjustSdk.a(Adjust.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

To reproduce, create an empty project in Unity. Import the SDK and build using the example scene. Build for archive. Libraries need to be build as archive or install to correctly support bitcode.

**Comment by uerceg** [comment]
Hi @epsmarkh 

Thanks for the detailed report. ATM, we are preparing Unity SDK update which will include this fix as well. Hopefully we'll release it this week, at latest point early next week.

Cheers.

**Comment by uerceg** [comment]
@epsmarkh Anything better regarding this issue when trying https://github.com/adjust/unity_sdk/releases/tag/v4.1.3 ?

**Comment by epsmarkh** [comment]
This version seems to work fine for us now. Thanks.
