### ISSUE TITLE
Adjust Post Process failing on Cloud Build

### ISSUE THREAD

**Issue by JackHCS** [adjust/unity_sdk#73]
Recently we've been unable to build an Android version of a project using the Unity Cloud Build service, it almost always cancels. Local builds using the Editor on Unity 5.3.5p6 for the same project still work fine though.
We added logs to the start and end of our Post Process functions to diagnose the issue. Unfortunately the build process never reaches the "Completed" log added to AdjustEditor.OnPostprocessBuild. After added more logging to verify that it is failing while waiting for the Python script to execute. It seems to get cancelled with a SIGTERM which seems like it's Cloud Build itself cancelling the build?

I've been in contact with Unity's support but so far their responses have been slow and few. They've confirmed that they run Python 2.7.10 and suggested there may be others with the same issue. I had hoped they'd look into any AdjustPostBuildAndroidLog.txt output to see whether it existed and what was in it but so far nothing on that.

Could using an older version of the SDK cause an issue? Local builds are fine so I haven't thought this could be an issue but we haven't updated in a few months so if there were any changes in Cloud Build that require us to update the SDK we wouldn't have them.

**Comment by uerceg** [comment]
Hi @JackHCS and thanks for reporting this.

In our SDK README we are assuming that Unity IDE is going to be used for app development and, like you said, with Unity IDE build process finished without any issues. We have noticed this behaviour maybe once so far and it seems like what ever cloud build system you are using is not very friendly towards Python post build scripts which should be executed as part of our SDK once Unity build has been initialised.

We were trying to figure out this as well, but no luck. Supporting some 3rd party ways of building the Unity app (like these cloud build systems you are mentioning) is not something we support, but we are always trying to make our SDK work in most use cases possible.

For issues like this one you are facing, we are having in our future Unity SDK updates to maybe abandon Python post build scripts and try to use `AdjustEditor.cs` class to perform all the work which post build scripts are doing at the moment. Hopefully, it will prevent issues like this in the future.

Cheers

**Comment by JackHCS** [comment]
Thanks for the response and explanation. 
When I've been talking about Cloud Build I mean this service https://unity3d.com/services/cloud-build. I'll continue following up with Unity themselves to see whether that goes anywhere.
If I have time I might look at the Python script and see if it's difficult to try to convert to a C# equivalent.

**Comment by uerceg** [comment]
Great, if you have any updates from the Unity, please share them in here with us as well. And also, if you are faster than us, feel free to submit the PR for the scripts replacement. :)

Cheers

**Comment by uerceg** [comment]
Hi @JackHCS  

Update is live now: https://github.com/adjust/unity_sdk/releases/tag/v4.10.0

Give it a try and let me know if it helped you with your issue.

Cheers

**Comment by uerceg** [comment]
Hi @JackHCS 

Any update on this issue?

**Comment by JackHCS** [comment]
Hello, I'm sorry for not finding time to reply before.
Unfortunately I am unable to give an answer. We've not had a chance to try the new release yet and I'm not sure when/if we will be able to so.
We've had an unexpected disruption on the business side which has left Adjust disabled in our project for the time being. Hopefully it will get resolved and we should be able to try the sdk update after. Sadly I have no idea how long it could take.

**Comment by uerceg** [comment]
I see. But this error should be fixed with our latest SDK version. Is it okay to close the issue and feel free to reopen it if this error still occurs with our latest Unity SDK version?

**Comment by JackHCS** [comment]
Yes I would agree it's a good idea to close this issue now.
