### ISSUE TITLE
Unable to get Google Play Services Advertising ID at start time

### ISSUE THREAD

**Issue by doxuto** [adjust/unity_sdk#82]
When I try to run the demo project in android platform, I get an error "Unable to get Google Play Services Advertising ID at start time". How to fix it? Thanks

**Comment by uerceg** [comment]
Hi @doxuto 

It means that you did not add the Google Play Services to your app's project. Instructions on how to do that can be found in here: https://github.com/adjust/unity_sdk#google-play-services

Please have in mind that this path is now with newer Google Play Services versions changed and if you go to your SDK root directory, you can find Google Play Services in this path:

```
{SDK_ROOT_DIR}/extras/google/m2repository/com/google/android/gms/
```

In there, you'll see something like this:

<img width="207" alt="screen shot 2016-10-07 at 08 49 45" src="https://cloud.githubusercontent.com/assets/1741635/19181100/0da03baa-8c6b-11e6-807e-b1f14ca7a1ea.png">

First folder named `play-services` probably contains entire Google Play Services library, but in order for our SDK to get what we need from the library, it is enough to add `play-services-analytics` folder only. In theory, that should do the trick.

Try it and let me know if it worked.

Cheers

**Comment by doxuto** [comment]
Hi uerceg.
 the issue assumes test on the simulator. I tried to test on the real device and the issue solved.

**Comment by uerceg** [comment]
Yeah, I mean, if Google Play Services are available on the testing device (or simulator), Google Play Ad Id will be read. If not, even though you have added Google Play Services properly to your app, it won't.

Anyway, glad that it worked for you!

Cheers

**Comment by HBiSoft** [comment]
For future readers, if you are using proguard, you should add the following:

    -keep public class com.google.android.gms.** { public protected *; }

**Comment by nicolastinkl** [comment]
Unable to get any Device IDs. Please check if Proguard is correctly set with Adjust SDK
