### ISSUE TITLE
Failed to read response and track session when sending data

### ISSUE THREAD

**Issue by pika-shiro** [adjust/unity_sdk#86]
Adjust Version: unity4.10.0(Sandbox-Mode)
Device: ASUS_Z00AD
Device-Android Version: 5.0

get this error in logcat for every event:

    E     Failed to read response. (Attempt to invoke virtual method 'com.android.okhttp.Route com.android.okhttp.Connection.getRoute()' on a null object reference)
    E     Failed to track session. (Runtime exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.okhttp.Route com.android.okhttp.Connection.getRoute()' on a null object reference)

Similar to this problem
[https://github.com/adjust/android_sdk/issues/228](url)

Below are debug-logs from both Adjust versions after first app-start:

**os_version 5.0**

    A			 SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
    D			 Attribution file not found
    D			 Activity state file not found
    D			 Session Callback parameters file not found
    D			 Session Partner parameters file not found
    I			 Google Play Services Advertising ID read correctly at start time
    V			 Foreground timer configured to fire after 60.0 seconds of starting and cycles every 60.0 seconds
    D			 Package queue file not found
    V			 Foreground timer starting
    V			 Subsession start
    D			 Added package 1 (session)
    V			 Path: /session
    V			 ClientSdk: unity4.10.0@android4.10.1
    V			 Parameters:
    V			 android_uuid xxxxx
    V			 api_level 21
    V			 app_token xxxxx
    V			 app_version xxxxx
    V			 attribution_deeplink 1
    V			 country JP
    V			 cpu_type x86
    V			 created_at 2016-10-13T11:46:18.970Z+0900
    V			 device_manufacturer asus
    V			 device_name ASUS_Z00AD
    V			 device_type phone
    V			 display_height 1920
    V			 display_width 1080
    V			 environment sandbox
    V			 event_buffering_enabled 0
    V			 gps_adid xxxxx
    V			 hardware_name LRX21V.JP-ASUS_Z00A-2.20.40.174_20160310_0673_user
    V			 language ja
    V			 needs_response_details 1
    V			 os_name android
    V			 os_version 5.0
    V			 package_name xxxxx
    V			 screen_density high
    V			 screen_format long
    V			 screen_size normal
    V			 session_count 1
    V			 tracking_enabled 1
    D			 Wrote Activity state: ec:0 sc:1 ssc:1 sl:0.0 ts:0.0 la:11:12:13 uuid:a203054a-e44b-4c3f-b6aa-174544dcaacc
    D			 Wrote Package queue: [session]
    V			 Foreground timer is already started
    V			 Subsession start
    V			 Time span since last activity too short for a new subsession
    D			 Package handler wrote 1 packages
    V			 Package handler is already sending
    E			 Failed to read response. (Attempt to invoke virtual method 'com.android.okhttp.Route com.android.okhttp.Connection.getRoute()' on a null object reference)
    E			 Failed to track session. (Runtime exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.okhttp.Route com.android.okhttp.Connection.getRoute()' on a null object reference)
    D			 Wrote Package queue: []
    D			 Launching failed session tracking listener
    D			 Package handler wrote 0 packages
    V			 Package handler can send

and it might be a little different 
this OS also occured simillar problem

**os_version  4.2.2**

    A			 SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
    D			 Attribution file not found
    D			 Activity state file not found
    D			 Session Callback parameters file not found
    D			 Session Partner parameters file not found
    I			 Google Play Services Advertising ID read correctly at start time
    V			 Foreground timer configured to fire after 60.0 seconds of starting and cycles every 60.0 seconds
    D			 Package queue file not found
    V			 Foreground timer starting
    V			 Subsession start
    D			 Added package 1 (session)
    V			 Path: /session
    V			 ClientSdk: unity4.10.0@android4.10.1
    V			 Parameters:
    V			 android_uuid xxxxx
    V			 api_level 17
    V			 app_token xxxxx
    V			 app_version xxxxx
    V			 attribution_deeplink 1
    V			 country JP
    V			 cpu_type armeabi-v7a
    V			 created_at 2016-10-13T12:00:40.648Z+0900
    V			 device_manufacturer Sony
    V			 device_name SO-02E
    V			 device_type phone
    V			 display_height 1776
    V			 display_width 1080
    V			 environment sandbox
    V			 event_buffering_enabled 0
    V			 gps_adid xxxxx
    V			 hardware_name 10.3.1.B.1.1
    V			 language ja
    V			 needs_response_details 1
    V			 os_name android
    V			 os_version 4.2.2
    V			 package_name xxxxx
    V			 screen_density high
    V			 screen_format normal
    V			 screen_size normal
    V			 session_count 1
    V			 tracking_enabled 1
    D			 Wrote Activity state: ec:0 sc:1 ssc:1 sl:0.0 ts:0.0 la:11:12:13 uuid:fd3c2f02-42b0-4751-ac9a-00ddb755b16a
    V			 Foreground timer is already started
    V			 Subsession start
    V			 Time span since last activity too short for a new subsession
    D			 Wrote Package queue: [session]
    D			 Package handler wrote 1 packages
    V			 Package handler is already sending
    E			 Failed to read response. (Socket is closed)
    E			 Failed to track session. (Request failed: java.net.SocketException: Socket is closed) Will retry later
    V			 Waiting for 64.6 seconds before retrying the 1 time
    D			 Launching failed session tracking listener
    V			 Foreground timer suspended with 37.4 seconds left
    V			 Subsession end

**os_version 4.1.2**

    A			 SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
    D			 Attribution file not found
    D			 Activity state file not found
    D			 Session Callback parameters file not found
    D			 Session Partner parameters file not found
    I			 Google Play Services Advertising ID read correctly at start time
    V			 Foreground timer configured to fire after 60.0 seconds of starting and cycles every 60.0 seconds
    D			 Package queue file not found
    V			 Foreground timer starting
    V			 Subsession start
    D			 Added package 1 (session)
    D			 Wrote Activity state: ec:0 sc:1 ssc:1 sl:0.0 ts:0.0 la:11:12:13 uuid:99f1055c-ed53-4d1f-8a3c-94f7e113e4a0
    V			 Foreground timer is already started
    V			 Subsession start
    V			 Time span since last activity too short for a new subsession
    V			 Path: /session
    V			 ClientSdk: unity4.10.0@android4.10.1
    V			 Parameters:
    V			 android_uuid xxxxx
    V			 api_level 16
    V			 app_token xxxxx
    V			 app_version xxxxx
    V			 attribution_deeplink 1
    V			 country JP
    V			 cpu_type armeabi-v7a
    V			 created_at 2016-10-13T12:10:37.756Z+0900
    V			 device_manufacturer samsung
    V			 device_name SC-06D
    V			 device_type phone
    V			 display_height 1280
    V			 display_width 720
    V			 environment sandbox
    V			 event_buffering_enabled 0
    V			 fb_id xxxxx
    V			 gps_adid xxxxx
    V			 hardware_name JZO54K.SC06DOMBMK2
    V			 language ja
    V			 needs_response_details 1
    V			 os_name android
    V			 os_version 4.1.2
    V			 package_name xxxxx
    V			 screen_density high
    V			 screen_format long
    V			 screen_size normal
    V			 session_count 1
    V			 tracking_enabled 1
    D			 Wrote Package queue: [session]
    D			 Package handler wrote 1 packages
    V			 Package handler is already sending
    E			 Failed to read response. (Socket is closed)
    E			 Failed to track session. (Request failed: java.net.SocketException: Socket is closed) Will retry later
    V			 Waiting for 89.6 seconds before retrying the 1 time
    D			 Launching failed session tracking listener

**Comment by uerceg** [comment]
Hi @pika-shiro 

Thanks for the report. We will release Unity 4.10.1 today and would like to hear from you if that version solved your issue. Will keep you posted in this issue once new version is live.

Cheers

**Comment by nonelse** [comment]
should be fixed with [v4.10.1](https://github.com/adjust/unity_sdk/releases/tag/v4.10.1)

**Comment by pika-shiro** [comment]
Thanks!!
new version(unity4.10.1) work very well!!
I described problems were all resolved!!
