### ISSUE TITLE
Adjust causes crash on start with Unity 5.5

### ISSUE THREAD

**Issue by christian-putzke** [adjust/unity_sdk#95]
Hi!
I can't get Adjust running with Unity 5.5. Our game crashes instantly on app start.
Is this a known issue? If I remove the SDK the game runs fine. Here is a screenshot from XCode which might help you if you don't know the issue yet.

<img width="458" alt="screen shot 2016-12-16 at 14 17 30" src="https://cloud.githubusercontent.com/assets/923446/21264128/d8029404-c39a-11e6-8004-8f8355a4c29b.png">

**Comment by uerceg** [comment]
Hi @christian-putzke 

Which Unity SDK version are you using? How are you adding the SDK to your Unity app - directly from code or by using prefab?

Cheers

**Comment by christian-putzke** [comment]
We are using Unity 5.5.0f3, Adjust SDK 4.10.3 and the SDK get's added by a prefab.

**Comment by uerceg** [comment]
And sorry, forgot to ask, Xcode version?

**Comment by christian-putzke** [comment]
The initialization happens manually though, from the code side.

**Comment by christian-putzke** [comment]
Xcode Version 8.1 (8B62)

**Comment by uerceg** [comment]
Regarding your upper comment ☝️ on the initialisation, you have `Start Manually` option checked on the prefab?

**Comment by christian-putzke** [comment]
Yep. Start Manually is checked.

**Comment by uerceg** [comment]
Thanks for the update, will be checked. Let you know as soon as possible if we manage to reproduce the issue or if we have any additional questions.

**Comment by uerceg** [comment]
@christian-putzke Any error message maybe being displayed in the Xcode log output?

**Comment by christian-putzke** [comment]
2016-12-16 14:40:43.704045 drp[490:130461] 	[Adjust]a: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing
2016-12-16 14:40:43.704457 drp[490:130461] 	[Adjust]v: Attribution file not found
2016-12-16 14:40:43.704694 drp[490:130461] 	[Adjust]v: Activity state file not found
2016-12-16 14:40:43.704923 drp[490:130600] -[UIDevice adjTrackingEnabled]: unrecognized selector sent to instance 0x1740358a0
2016-12-16 14:40:43.714431 drp[490:130461] 	[Adjust]d: Adjust already in online mode
2016-12-16 14:40:43.716461 drp[490:130600] Uncaught exception: NSInvalidArgumentException: -[UIDevice adjTrackingEnabled]: unrecognized selector sent to instance 0x1740358a0
(
	0   CoreFoundation                      0x0000000184abe1d8 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001834f855c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000184ac5278 <redacted> + 0
	3   CoreFoundation                      0x0000000184ac2278 <redacted> + 916
	4   CoreFoundation                      0x00000001849bc59c _CF_forwarding_prep_0 + 92
	5   drp                                 0x0000000101789b24 -[ADJDeviceInfo initWithSdkPrefix:] + 248
	6   drp                                 0x0000000101789a0c +[ADJDeviceInfo deviceInfoWithSdkPrefix:] + 72
	7   drp                                 0x0000000101777aa0 -[ADJActivityHandler initI:sessionParametersActionsArray:] + 280
	8   drp                                 0x0000000101788400 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 48
	9   libdispatch.dylib                   0x0000000104fad25c _dispatch_call_block_and_release + 24
	10  libdispatch.dylib                   0x0000000104fad21c _dispatch_client_callout + 16
	11  libdispatch.dylib                   0x0000000104fbab54 _dispatch_queue_serial_drain + 1136
	12  libdispatch.dylib                   0x0000000104fb0ce4 _dispatch_queue_invoke + 672
	13  libdispatch.dylib                   0x0000000104fbb0f0 _dispatch_queue_override_invoke + 496
	14  libdispatch.dylib                   0x0000000104fbce6c _dispatch_root_queue_drain + 584
	15  libdispatch.dylib                   0x0000000104fbcbb8 _dispatch_worker_thread3 + 140
	16  libsystem_pthread.dylib             0x0000000183b522b8 _pthread_wqthread + 1288
	17  libsystem_pthread.dylib             0x0000000183b51da4 start_wqthread + 4
)
2016-12-16 14:40:43.716621 drp[490:130461] Warning: Libinfo call to mDNSResponder on main thread
2016-12-16 14:40:43.717535 drp[490:130600] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIDevice adjTrackingEnabled]: unrecognized selector sent to instance 0x1740358a0'
*** First throw call stack:
(0x184abe1c0 0x1834f855c 0x184ac5278 0x184ac2278 0x1849bc59c 0x101789b24 0x101789a0c 0x101777aa0 0x101788400 0x104fad25c 0x104fad21c 0x104fbab54 0x104fb0ce4 0x104fbb0f0 0x104fbce6c 0x104fbcbb8 0x183b522b8 0x183b51da4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by uerceg** [comment]
Aham, interesting.

Is `AdjustEditor.cs` part of you `Assets/Editor` folder? In there post build script should run after building your Xcode project from Unity 5 IDE and add necessary flags to the Xcode project. Somehow for you seems that it didn't.

You can solve this by going to your Xcode project settings, locate `Other Linker Flags` and add `-ObjC` flag.

Lemme know if it worked.

Cheers

**Comment by christian-putzke** [comment]
I think I've found the issue. I've created my Xcode project on a windows machine but the RunPostBuildScript method of the AdjustEditor.cs script is using the UNITY_EDITOR_OSX symbol at line 48 so it won't get executed.

**Comment by uerceg** [comment]
Glad it worked!

Aha, interesting. So you are using Unity 5 IDE on Windows? How are you running the app from Xcode afterwards? Mac or maybe some VM?

**Comment by christian-putzke** [comment]
I'm actively using Unity 5 on Windows. We are creating builds through Jenkins on an iMac but as I'm currently evaluating Unity 5.5 I've just updated my Windows machine so far and exported the Xcode project on my Windows machine as well.

**Comment by christian-putzke** [comment]
Thanks for you help! Is there any specific reason for the `UNITY_EDITOR_OSX` symbol around the Xcode project generation? Unity officially allows you to export to a Xcode project on Windows machines so I might be interesting to remove or change the symbol checks here ;)

**Comment by uerceg** [comment]
No problemo!

You can try removing these checks so that everything gets added to the Xcode project what is needed to be done by our post build script. If you prefer doing stuff manually, then this is what's being done by post build script: https://github.com/adjust/unity_sdk#post-build-ios

But yep, what you said makes sense. We're adding this thing to roadmap of our next Unity SDK release and we'll make it as generic as possible regardless of the platform on which Unity IDE is running.

Thanks for noticing this!

**Comment by uerceg** [comment]
Hi @christian-putzke 

We have just released v4.11.0: https://github.com/adjust/unity_sdk/releases/tag/v4.11.0

Can you give it a try and see if this problem still persist?

Thanks in advance.

Cheers

**Comment by uerceg** [comment]
@christian-putzke Any update on this?

**Comment by christian-putzke** [comment]
Looks good for me. Thanks!
